---

- include: git.yml
  tags: git

- name: 'Copy cli_aliases file'
  copy:
    src    : 'cli_aliases'
    dest   : '{{ ansible_env.HOME }}/.cli_aliases'
    owner  : '{{ ansible_user }}'
    group  : '{{ ansible_user }}'
    mode   : '0644'
    backup : 'yes'

- include: zsh/main.yml
  tags: zsh

- name: make sure cli_aliases is sourced [.bashrc]
  blockinfile:
    path: '{{ ansible_env.HOME }}/.bashrc'
    backup: 'yes'
    state: 'present'
    marker_begin: 'CLI ALIASES'
    marker_end: 'CLI ALIASES'
    block: |
      if [ -f {{ ansible_env.HOME }}/.cli_aliases ]; then
        . {{ ansible_env.HOME }}/.cli_aliases
      fi
