---

- name: add spotify apt key
  apt_key:
    keyserver: 'hkp://keyserver.ubuntu.com:80'
    id: '{{ item }}'
    state: 'present'
  with_items:
    - '931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90'
    - '2EBF997C15BDA244B6EBF5D84773BD5E130D1D45'
  become: true

- name: add spotify apt repository
  apt_repository:
    repo: 'deb http://repository.spotify.com stable non-free'
    state: 'present'
    update_cache: true
  become: true

- name: install spotify
  apt:
    name: 'spotify-client'
    state: 'present'
  become: true
