---

- name: 'install emacs'
  apt:
    name: 'emacs'
    state: 'present'
  become: true

- name: 'create the systemd user directory'
  file:
    path: '{{ ansible_env.HOME }}/.config/systemd/user'
    state: 'directory'
    mode: 0700

- name: 'install emacs server unit file'
  copy:
    src: 'emacs.service'
    dest: '{{ ansible_env.HOME }}/.config/systemd/user/emacs.service'
    mode: 0644

- name: 'enable emacs service'
  systemd:
    name: 'emacs'
    scope: 'user'
    enabled: 'yes'
    daemon_reload: 'yes'

- name: 'start emacs service'
  systemd:
    name: 'emacs'
    scope: 'user'
    state: 'started'
    daemon_reload: 'yes'

- debug:
    msg: |
      You will need to retrieve the new Melpa GPG key to be able to install
      new packages. Run:

      gpg --homedir ~/.emacs.d/elpa/gnupg --receive-keys 066DAFCB81E42C40

      More information:
      https://emacs.stackexchange.com/questions/233/how-to-proceed-on-package-el-signature-check-failure

# M-x package-refresh-packages
# M-x install-package zenburn-theme
# M-x customize-themes # or probably copying the config from `files` will suffice

# - name: 'copy emacs config'
#   copy:
#    src: 'emacs'
#    dest: '{{ ansible_env.HOME }}/.emacs'
#    mode: '0600'

