---

- include: install_tilda.yml
  tags: tilda

- include: install_synapse.yml
  tags: synapse

- include: install_shutter.yml
  tags: shutter

- include: keyboard_shortcuts/configure_keyboard_shortcuts.yml
  tags: shortcuts
