---

- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- include: install_vim.yml
  tags: vim

- include: install_tilda.yml
  tags: tilda

- include: install_synapse.yml
  tags: synapse

- include: install_shutter.yml
  tags: shutter

- include: keyboard_shortcuts/configure_keyboard_shortcuts.yml
  tags: shortcuts

- include: install_kubectl.yml
  tags: kubectl

- include: install_terraform.yml
  tags: terraform