---

- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- include: install_tar_excludes.yml
  tags: tar

- include: install_vim.yml
  tags: vim

- include: install_emacs.yml
  tags: emacs

- include: install_tilda.yml
  tags: tilda

- include: install_synapse.yml
  tags: synapse

- include: install_shutter.yml
  tags: shutter

- include: dconf/configure_dconf.yml
  tags: dconf

- include: install_terraform.yml
  tags: terraform

- include: install_kubectl.yml
  tags:
    - kubectl
    - minikube
    - helm

- include: install_virtualbox.yml
  tags:
    - virtualbox
    - minikube

- include: install_minikube.yml
  tags:
    - minikube
    - minikube-only

- include: install_helm.yml
  tags:
    - helm
    - helm-only

- include: install_gcloud.yml
  tags:
    - gcloud

- include: install_spotify.yml
  tags:
    - spotify

- include: install_udev_rules.yml
  tags:
    - udev
