---

- name: change zsh theme
  lineinfile:
    regexp: "^ZSH_THEME"
    line: 'ZSH_THEME="philips"'
    path: "{{ ansible_env.HOME }}/.zshrc"

- name: configure zsh plugins
  lineinfile:
    regexp: "^plugins"
    line: 'plugins=(git docker kube-ps1)'
    path: "{{ ansible_env.HOME }}/.zshrc"

- name: configure current user's shell to zsh
  user:
    name: '{{ ansible_env.USER }}'
    shell: '/bin/zsh'
  become: true

- name: copy own zshrc configuration
  copy:
    src: 'zshrc'
    dest: '{{ ansible_env.HOME }}/.my-zshrc'

- name: source own zshrc from main one
  blockinfile:
    path: '{{ ansible_env.HOME }}/.zshrc'
    state: 'present'
    marker_begin: 'BEGIN OWN ZSH SOURCE'
    marker_end: 'END OWN ZSH SOURCE'
    block: |
      if [ -f "$HOME/.my-zshrc" ]; then
        source "$HOME/.my-zshrc"
      fi
