---

- name: change zsh theme
  lineinfile:
    regexp: "^ZSH_THEME"
    line: 'ZSH_THEME="philips"'
    path: "{{ ansible_env.HOME }}/.zshrc"

- name: make sure cli_aliases is sourced [.zshrc]
  blockinfile:
    path: '{{ ansible_env.HOME }}/.zshrc'
    backup: 'yes'
    state: 'present'
    marker_begin: 'BEGIN CLI ALIASES'
    marker_end: 'END CLI ALIASES'
    block: |
      if [ -f {{ ansible_env.HOME }}/.cli_aliases ]; then
        . {{ ansible_env.HOME }}/.cli_aliases
      fi

- name: add kubectl completion
  blockinfile:
    path: '{{ ansible_env.HOME }}/.zshrc'
    backup: 'yes'
    state: 'present'
    marker_begin: 'BEGIN KUBECTL ZSH COMPLETION'
    marker_end: 'END KUBECTL ZSH COMPLETION'
    block: |
      if type kubectl > /dev/null; then
        source <(kubectl completion zsh)
      fi

- name: configure current user's shell to zsh
  user:
    name: '{{ ansible_env.USER }}'
    shell: '/bin/zsh'
  become: true
