---

- name: 'copy emacs config'
  copy:
   src: 'emacs'
   dest: '{{ ansible_env.HOME }}/.emacs'
   mode: '0600'

- name: 'create the systemd user directory'
  file:
    path: '{{ ansible_env.HOME }}/.config/systemd/user'
    state: 'directory'
    mode: 0700

- name: 'install emacs server unit file'
  copy:
    src: 'emacs.service'
    dest: '{{ ansible_env.HOME }}/.config/systemd/user/emacs.service'
    mode: 0644

- name: 'enable emacs service'
  systemd:
    name: 'emacs'
    scope: 'user'
    enabled: 'yes'
    daemon_reload: 'yes'

- name: 'start emacs service'
  systemd:
    name: 'emacs'
    scope: 'user'
    state: 'started'
    daemon_reload: 'yes'

- debug:
    msg: 'You will need to manually edit pam.d if using ecryptfs https://unix.stackexchange.com/questions/417162/use-systemd-user-services-with-ecryptfs'
