---

- name: filter custom shortcuts list
  set_fact:
    custom_shortcuts_list: "{{ dconf.keys() | select('match', '^.*custom[0-9]+$') | list | map('regex_replace', '.*/(custom[0-9]+)$', '\\1') | list }}"

# there does not seem to be an easy way in ansible to make a
# list of quoted strings (without the unicode prefix)
- name: create custom shortcuts list in gvariant format
  set_fact:
    custom_shortcuts: "['{{ \"', '\".join(custom_shortcuts_list) }}']"

- name: add all shortcuts to the list of keybindings
  dconf:
    key: '/org/cinnamon/desktop/keybindings/custom-list'
    value: "{{ custom_shortcuts }}"
    state: 'present'
